class IntParam:
    def __init__(self, low: int, high: int, size: int): ...

    @property
    def bounds(self) -> list[tuple]: ...


def suggest_int(low: int, high: int, size: int = 1) -> IntParam: ...
